### ISSUE TITLE
 The magic number is not match

### ISSUE THREAD

**Issue by hutuxiansheng** [althafvly/AmlogicKitchen#1]
.....................
Amlogic Kitchen
.....................
.....................
Select level 1,2 or 3: 
1
Deleting existing level1
.....................
Amlogic Kitchen
.....................
Files in input dir (*.img)
1 - boot
.....................
Enter a file name :
boot
[Msg]Image package version 0x2144494f
[ERR]f(AmlImagePack.cpp)L298:Image check error! The magic number is not match
[ERR]f(AmlImagePack.cpp)L1635:Image file check failed!
Done.

**Comment by althafvly** [comment]
@hutuxiansheng you can't extract boot.img with this script. use aik https://github.com/osm0sis/Android-Image-Kitchen
