### ISSUE TITLE
pack_zip_to_aml "DDR.USB is missing, copy DDR.USB to level1 dir"  And create workflow xml file  failed

### ISSUE THREAD

**Issue by zengfr** [althafvly/AmlogicKitchen#11]
Python 3.9.13
.....................
Amlogic Kitchen
.....................
Files in input dir (*.zip)
1 - B863AV3.2M-220821_fota
.....................
Enter a file name :B863AV3.2M-220821_fota

7-Zip (a) 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 554403244 bytes (529 MiB)

Extracting archive: in\B863AV3.2M-220821_fota.zip
--
Path = in\B863AV3.2M-220821_fota.zip
Type = zip
Physical Size = 554403244
Comment = signed by SignApk

Everything is Ok

Files: 25
Size:       560904600
Compressed: 554403244
sdat2img binary - version: 1.2

Android Nougat 7.x / Oreo 8.x detected!

Skipping command erase...
Copying 1 blocks into position 0...
Skipping command zero...
Copying 1 blocks into position 1...
Copying 4 blocks into position 9...
Copying 111 blocks into position 75...
Skipping command zero...
Done! Output image: F:\AmlogicKitchen-master\tmp\odm.img
已复制         1 个文件。
sdat2img binary - version: 1.2

Android Nougat 7.x / Oreo 8.x detected!

Skipping command erase...
Copying 1 blocks into position 0...
Copying 365 blocks into position 15374...
Copying 512 blocks into position 14862...
Copying 427 blocks into position 14346...
Copying 85 blocks into position 14777...
Copying 512 blocks into position 13834...
Copying 512 blocks into position 13322...
Copying 512 blocks into position 12810...
Copying 512 blocks into position 12298...
Copying 512 blocks into position 11786...
Copying 512 blocks into position 11274...
Copying 512 blocks into position 10762...
Copying 512 blocks into position 10250...
Copying 512 blocks into position 9738...
Copying 512 blocks into position 9226...
Copying 512 blocks into position 8714...
Copying 512 blocks into position 8202...
Copying 512 blocks into position 7690...
Copying 512 blocks into position 7178...
Copying 512 blocks into position 6666...
Copying 512 blocks into position 6154...
Copying 512 blocks into position 5642...
Copying 512 blocks into position 4618...
Copying 1 blocks into position 1...
Copying 4 blocks into position 9...
Copying 507 blocks into position 523...
Copying 512 blocks into position 5130...
Copying 512 blocks into position 3082...
Copying 512 blocks into position 3594...
Copying 512 blocks into position 2570...
Copying 512 blocks into position 1030...
Copying 17 blocks into position 2056...
Copying 477 blocks into position 2074...
Copying 18 blocks into position 2552...
Copying 235 blocks into position 1542...
Copying 277 blocks into position 1779...
Copying 512 blocks into position 4106...
Skipping command zero...
Skipping command zero...
Done! Output image: F:\AmlogicKitchen-master\tmp\product.img
已复制         1 个文件。
sdat2img binary - version: 1.2

Android Nougat 7.x / Oreo 8.x detected!

Skipping command erase...
Copying 159 blocks into position 38250...
Copying 10 blocks into position 38429...
Copying 13 blocks into position 38457...
Copying 2 blocks into position 38473...
Copying 44 blocks into position 38480...
Copying 38 blocks into position 38532...
Copying 1 blocks into position 38571...
Copying 2 blocks into position 38573...
Copying 243 blocks into position 38576...
Copying 512 blocks into position 37738...
Copying 512 blocks into position 37226...
Copying 512 blocks into position 36714...
Copying 512 blocks into position 36202...
Copying 512 blocks into position 35690...
Copying 512 blocks into position 35178...
Copying 512 blocks into position 34666...
Copying 512 blocks into position 34154...
Copying 512 blocks into position 33642...
Copying 89 blocks into position 32678...
Copying 2 blocks into position 32768...
Copying 1 blocks into position 32793...
Copying 420 blocks into position 33222...
Copying 383 blocks into position 32152...
Copying 15 blocks into position 32542...
Copying 114 blocks into position 32564...
Copying 512 blocks into position 31640...
Copying 512 blocks into position 31128...
Copying 512 blocks into position 30616...
Copying 512 blocks into position 30104...
Copying 512 blocks into position 29592...
Copying 57 blocks into position 29075...
Copying 1 blocks into position 29133...
Copying 454 blocks into position 29138...
Copying 512 blocks into position 28563...
Copying 512 blocks into position 28051...
Copying 512 blocks into position 27539...
Copying 512 blocks into position 27027...
Copying 512 blocks into position 26515...
Copying 512 blocks into position 26003...
Copying 512 blocks into position 25491...
Copying 512 blocks into position 24979...
Copying 512 blocks into position 24467...
Copying 34 blocks into position 23951...
Copying 478 blocks into position 23989...
Copying 512 blocks into position 23439...
Copying 512 blocks into position 22927...
Copying 512 blocks into position 22415...
Copying 512 blocks into position 21903...
Copying 512 blocks into position 21391...
Copying 3 blocks into position 20865...
Copying 11 blocks into position 20875...
Copying 498 blocks into position 20893...
Copying 1 blocks into position 0...
Copying 512 blocks into position 20353...
Copying 67 blocks into position 81852...
Copying 207 blocks into position 19828...
Copying 11 blocks into position 20041...
Copying 294 blocks into position 20059...
Copying 18 blocks into position 81231...
Copying 3 blocks into position 81252...
Copying 3 blocks into position 81258...
Copying 28 blocks into position 81264...
Copying 5 blocks into position 81296...
Copying 5 blocks into position 81305...
Copying 5 blocks into position 81314...
Copying 6 blocks into position 81323...
Copying 5 blocks into position 81333...
Copying 5 blocks into position 81342...
Copying 5 blocks into position 81351...
Copying 5 blocks into position 81360...
Copying 6 blocks into position 81369...
Copying 5 blocks into position 81379...
Copying 22 blocks into position 81388...
Copying 4 blocks into position 81413...
Copying 4 blocks into position 81420...
Copying 3 blocks into position 81428...
Copying 4 blocks into position 81435...
Copying 4 blocks into position 81442...
Copying 4 blocks into position 81449...
Copying 4 blocks into position 81456...
Copying 3 blocks into position 81464...
Copying 3 blocks into position 81471...
Copying 3 blocks into position 81478...
Copying 2 blocks into position 81485...
Copying 4 blocks into position 81488...
Copying 3 blocks into position 81493...
Copying 3 blocks into position 81497...
Copying 37 blocks into position 81501...
Copying 1 blocks into position 81541...
Copying 6 blocks into position 81545...
Copying 7 blocks into position 81552...
Copying 8 blocks into position 81560...
Copying 6 blocks into position 81569...
Copying 6 blocks into position 81576...
Copying 6 blocks into position 81583...
Copying 261 blocks into position 81591...
Copying 512 blocks into position 19316...
Copying 436 blocks into position 80710...
Copying 3 blocks into position 81149...
Copying 4 blocks into position 81155...
Copying 69 blocks into position 81162...
Copying 512 blocks into position 18804...
Copying 151 blocks into position 80177...
Copying 1 blocks into position 80330...
Copying 55 blocks into position 80339...
Copying 2 blocks into position 80403...
Copying 1 blocks into position 80406...
Copying 302 blocks into position 80408...
Copying 512 blocks into position 18292...
Copying 59 blocks into position 79663...
Copying 453 blocks into position 79724...
Copying 512 blocks into position 17780...
Copying 512 blocks into position 79151...
Copying 512 blocks into position 17268...
Copying 39 blocks into position 78593...
Copying 38 blocks into position 78644...
Copying 107 blocks into position 78697...
Copying 42 blocks into position 78805...
Copying 36 blocks into position 78848...
Copying 107 blocks into position 78899...
Copying 42 blocks into position 79007...
Copying 101 blocks into position 79050...
Copying 512 blocks into position 16756...
Copying 297 blocks into position 78057...
Copying 127 blocks into position 78366...
Copying 88 blocks into position 78505...
Copying 512 blocks into position 16244...
Copying 512 blocks into position 77545...
Copying 512 blocks into position 15732...
Copying 512 blocks into position 77033...
Copying 512 blocks into position 15220...
Copying 40 blocks into position 76495...
Copying 43 blocks into position 76536...
Copying 22 blocks into position 76581...
Copying 82 blocks into position 76618...
Copying 46 blocks into position 76701...
Copying 92 blocks into position 76748...
Copying 19 blocks into position 76842...
Copying 81 blocks into position 76862...
Copying 19 blocks into position 76945...
Copying 68 blocks into position 76965...
Copying 512 blocks into position 14708...
Copying 12 blocks into position 75917...
Copying 129 blocks into position 75944...
Copying 22 blocks into position 76075...
Copying 129 blocks into position 76112...
Copying 22 blocks into position 76243...
Copying 129 blocks into position 76280...
Copying 22 blocks into position 76411...
Copying 47 blocks into position 76448...
Copying 512 blocks into position 14196...
Copying 145 blocks into position 75396...
Copying 32 blocks into position 75543...
Copying 121 blocks into position 75576...
Copying 32 blocks into position 75699...
Copying 121 blocks into position 75732...
Copying 32 blocks into position 75855...
Copying 29 blocks into position 75888...
Copying 512 blocks into position 13684...
Copying 512 blocks into position 74884...
Copying 512 blocks into position 13172...
Copying 512 blocks into position 74372...
Copying 512 blocks into position 12660...
Copying 512 blocks into position 73860...
Copying 512 blocks into position 12148...
Copying 512 blocks into position 73348...
Copying 512 blocks into position 11636...
Copying 512 blocks into position 72836...
Copying 170 blocks into position 11117...
Copying 134 blocks into position 11289...
Copying 208 blocks into position 11428...
Copying 512 blocks into position 72324...
Copying 512 blocks into position 10605...
Copying 512 blocks into position 71812...
Copying 512 blocks into position 10093...
Copying 512 blocks into position 71300...
Copying 512 blocks into position 9581...
Copying 512 blocks into position 70788...
Copying 512 blocks into position 9069...
Copying 512 blocks into position 70276...
Copying 512 blocks into position 8557...
Copying 512 blocks into position 69764...
Copying 332 blocks into position 8036...
Copying 44 blocks into position 8371...
Copying 1 blocks into position 8420...
Copying 135 blocks into position 8422...
Copying 512 blocks into position 69252...
Copying 512 blocks into position 7524...
Copying 512 blocks into position 68740...
Copying 512 blocks into position 7012...
Copying 512 blocks into position 68228...
Copying 512 blocks into position 6500...
Copying 512 blocks into position 67716...
Copying 512 blocks into position 5988...
Copying 512 blocks into position 67204...
Copying 512 blocks into position 5476...
Copying 512 blocks into position 66692...
Copying 512 blocks into position 4452...
Copying 512 blocks into position 66180...
Copying 23 blocks into position 1...
Copying 75 blocks into position 25...
Copying 414 blocks into position 454...
Copying 18 blocks into position 47576...
Copying 33 blocks into position 47601...
Copying 1 blocks into position 47637...
Copying 5 blocks into position 47645...
Copying 239 blocks into position 47656...
Copying 1 blocks into position 65536...
Copying 215 blocks into position 65965...
Copying 512 blocks into position 4964...
Copying 436 blocks into position 47026...
Copying 33 blocks into position 47469...
Copying 1 blocks into position 47505...
Copying 33 blocks into position 47513...
Copying 1 blocks into position 47549...
Copying 8 blocks into position 47568...
Copying 512 blocks into position 2404...
Copying 512 blocks into position 46514...
Copying 512 blocks into position 1380...
Copying 512 blocks into position 46002...
Skipping command zero...
Copying 512 blocks into position 45490...
Copying 512 blocks into position 44978...
Copying 512 blocks into position 3428...
Copying 512 blocks into position 44466...
Copying 512 blocks into position 2916...
Copying 512 blocks into position 43954...
Copying 512 blocks into position 1892...
Copying 512 blocks into position 43442...
Copying 512 blocks into position 3940...
Copying 206 blocks into position 42927...
Copying 306 blocks into position 43136...
Copying 512 blocks into position 868...
Copying 459 blocks into position 42412...
Copying 53 blocks into position 42874...
Copying 512 blocks into position 41900...
Copying 125 blocks into position 41385...
Copying 387 blocks into position 41513...
Copying 512 blocks into position 40873...
Copying 39 blocks into position 40358...
Copying 473 blocks into position 40400...
Copying 281 blocks into position 39843...
Copying 231 blocks into position 40127...
Copying 512 blocks into position 39331...
Copying 512 blocks into position 38819...
Skipping command zero...
Skipping command zero...
Done! Output image: F:\AmlogicKitchen-master\tmp\vendor.img
已复制         1 个文件。
sdat2img binary - version: 1.2

Android Nougat 7.x / Oreo 8.x detected!

Skipping command erase...
Copying 512 blocks into position 121892...
Copying 512 blocks into position 121380...
Copying 512 blocks into position 120868...
Copying 512 blocks into position 307112...
Copying 512 blocks into position 120356...
Copying 512 blocks into position 306600...
Copying 512 blocks into position 119844...
Copying 512 blocks into position 306088...
Copying 512 blocks into position 119332...
Copying 512 blocks into position 305576...
Copying 512 blocks into position 118820...
Copying 512 blocks into position 305064...
Copying 512 blocks into position 118308...
Copying 512 blocks into position 304552...
Copying 512 blocks into position 117796...
Copying 512 blocks into position 304040...
Copying 512 blocks into position 117284...
Copying 512 blocks into position 303528...
Copying 512 blocks into position 116772...
Copying 512 blocks into position 303016...
Copying 512 blocks into position 116260...
Copying 512 blocks into position 302504...
Copying 512 blocks into position 115748...
Copying 322 blocks into position 301987...
Copying 4 blocks into position 302311...
Copying 186 blocks into position 302318...
Copying 512 blocks into position 115236...
Copying 512 blocks into position 301475...
Copying 512 blocks into position 114724...
Copying 512 blocks into position 300963...
Copying 512 blocks into position 114212...
Copying 512 blocks into position 300451...
Copying 512 blocks into position 113700...
Copying 512 blocks into position 299939...
Copying 512 blocks into position 113188...
Copying 512 blocks into position 299427...
Copying 512 blocks into position 112676...
Copying 512 blocks into position 298915...
Copying 512 blocks into position 112164...
Copying 512 blocks into position 298403...
Copying 512 blocks into position 111652...
Copying 512 blocks into position 297891...
Copying 512 blocks into position 111140...
Copying 512 blocks into position 297379...
Copying 512 blocks into position 110628...
Copying 512 blocks into position 296867...
Copying 512 blocks into position 110116...
Copying 512 blocks into position 296355...
Copying 512 blocks into position 109604...
Copying 512 blocks into position 295843...
Copying 512 blocks into position 109092...
Copying 172 blocks into position 261971...
Copying 1 blocks into position 262144...
Copying 2 blocks into position 294912...
Copying 1 blocks into position 294993...
Copying 336 blocks into position 295507...
Copying 512 blocks into position 108580...
Copying 512 blocks into position 261459...
Copying 512 blocks into position 108068...
Copying 512 blocks into position 260947...
Copying 512 blocks into position 107556...
Copying 512 blocks into position 260435...
Copying 512 blocks into position 107044...
Copying 512 blocks into position 259923...
Copying 512 blocks into position 106532...
Copying 512 blocks into position 259411...
Copying 368 blocks into position 106018...
Copying 144 blocks into position 106388...
Copying 512 blocks into position 258899...
Copying 322 blocks into position 105505...
Copying 190 blocks into position 105828...
Copying 512 blocks into position 258387...
Copying 36 blocks into position 104990...
Copying 316 blocks into position 105027...
Copying 160 blocks into position 105345...
Copying 512 blocks into position 257875...
Copying 474 blocks into position 104477...
Copying 38 blocks into position 104952...
Copying 512 blocks into position 257363...
Copying 512 blocks into position 103965...
Copying 512 blocks into position 256851...
Copying 512 blocks into position 103453...
Copying 512 blocks into position 256339...
Copying 512 blocks into position 102941...
Copying 352 blocks into position 255826...
Copying 160 blocks into position 256179...
Copying 512 blocks into position 102429...
Copying 512 blocks into position 255314...
Copying 512 blocks into position 101917...
Copying 512 blocks into position 254802...
Copying 6 blocks into position 101402...
Copying 95 blocks into position 101410...
Copying 411 blocks into position 101506...
Copying 512 blocks into position 254290...
Copying 500 blocks into position 100888...
Copying 9 blocks into position 101389...
Copying 3 blocks into position 101399...
Copying 512 blocks into position 253778...
Copying 512 blocks into position 100376...
Copying 512 blocks into position 253266...
Copying 512 blocks into position 99864...
Copying 512 blocks into position 252754...
Copying 162 blocks into position 99351...
Copying 350 blocks into position 99514...
Copying 512 blocks into position 252242...
Copying 37 blocks into position 65477...
Copying 19 blocks into position 65516...
Copying 1 blocks into position 65536...
Copying 2 blocks into position 98304...
Copying 1 blocks into position 98385...
Copying 452 blocks into position 98899...
Copying 512 blocks into position 251730...
Copying 130 blocks into position 64961...
Copying 319 blocks into position 65093...
Copying 63 blocks into position 65414...
Copying 512 blocks into position 251218...
Copying 246 blocks into position 64444...
Copying 121 blocks into position 64691...
Copying 134 blocks into position 64814...
Copying 11 blocks into position 64950...
Copying 512 blocks into position 250706...
Copying 512 blocks into position 63932...
Copying 512 blocks into position 250194...
Copying 512 blocks into position 63420...
Copying 198 blocks into position 249681...
Copying 314 blocks into position 249880...
Copying 512 blocks into position 62908...
Copying 512 blocks into position 249169...
Copying 512 blocks into position 62396...
Copying 512 blocks into position 248657...
Copying 512 blocks into position 61884...
Copying 512 blocks into position 248145...
Copying 512 blocks into position 61372...
Copying 512 blocks into position 247633...
Copying 512 blocks into position 60860...
Copying 143 blocks into position 247065...
Copying 30 blocks into position 247209...
Copying 2 blocks into position 247257...
Copying 1 blocks into position 247261...
Copying 1 blocks into position 247264...
Copying 2 blocks into position 247266...
Copying 1 blocks into position 247273...
Copying 1 blocks into position 247275...
Copying 331 blocks into position 247302...
Copying 512 blocks into position 60348...
Copying 129 blocks into position 246511...
Copying 21 blocks into position 246659...
Copying 362 blocks into position 246703...
Copying 512 blocks into position 59836...
Copying 387 blocks into position 245947...
Copying 23 blocks into position 246335...
Copying 5 blocks into position 246376...
Copying 1 blocks into position 246382...
Copying 3 blocks into position 246385...
Copying 2 blocks into position 246393...
Copying 91 blocks into position 246420...
Copying 512 blocks into position 59324...
Copying 512 blocks into position 245435...
Copying 512 blocks into position 58812...
Copying 512 blocks into position 244923...
Copying 512 blocks into position 58300...
Copying 512 blocks into position 244411...
Copying 512 blocks into position 57788...
Copying 512 blocks into position 243899...
Copying 512 blocks into position 57276...
Copying 512 blocks into position 243387...
Copying 512 blocks into position 56764...
Copying 512 blocks into position 242875...
Copying 512 blocks into position 56252...
Copying 512 blocks into position 242363...
Copying 512 blocks into position 55740...
Copying 335 blocks into position 241844...
Copying 177 blocks into position 242186...
Copying 512 blocks into position 55228...
Copying 512 blocks into position 241332...
Copying 512 blocks into position 54716...
Copying 512 blocks into position 240820...
Copying 512 blocks into position 54204...
Copying 512 blocks into position 240308...
Copying 512 blocks into position 53692...
Copying 315 blocks into position 239785...
Copying 13 blocks into position 240102...
Copying 184 blocks into position 240124...
Copying 512 blocks into position 53180...
Copying 512 blocks into position 239273...
Copying 512 blocks into position 52668...
Copying 512 blocks into position 238761...
Copying 512 blocks into position 52156...
Copying 512 blocks into position 238249...
Copying 512 blocks into position 51644...
Copying 512 blocks into position 237737...
Copying 512 blocks into position 51132...
Copying 512 blocks into position 237225...
Copying 512 blocks into position 50620...
Copying 512 blocks into position 236713...
Copying 512 blocks into position 50108...
Copying 512 blocks into position 236201...
Copying 512 blocks into position 49596...
Copying 512 blocks into position 235689...
Copying 100 blocks into position 49083...
Copying 412 blocks into position 49184...
Copying 512 blocks into position 235177...
Copying 512 blocks into position 48571...
Copying 512 blocks into position 234665...
Copying 512 blocks into position 48059...
Copying 408 blocks into position 234148...
Copying 104 blocks into position 234561...
Copying 512 blocks into position 47547...
Copying 512 blocks into position 233636...
Copying 512 blocks into position 47035...
Copying 512 blocks into position 233124...
Copying 512 blocks into position 46523...
Copying 512 blocks into position 232612...
Copying 512 blocks into position 46011...
Copying 79 blocks into position 1...
Copying 160 blocks into position 81...
Copying 273 blocks into position 595...
Copying 512 blocks into position 868...
Skipping command zero...
Skipping command zero...
Copying 512 blocks into position 1892...
Copying 512 blocks into position 1380...
Copying 512 blocks into position 45499...
Copying 512 blocks into position 44987...
Copying 512 blocks into position 44475...
Copying 512 blocks into position 43963...
Copying 512 blocks into position 43451...
Copying 512 blocks into position 42939...
Copying 512 blocks into position 42427...
Copying 76 blocks into position 41911...
Copying 5 blocks into position 41988...
Copying 431 blocks into position 41996...
Copying 512 blocks into position 41399...
Copying 512 blocks into position 40887...
Copying 512 blocks into position 40375...
Copying 512 blocks into position 39863...
Copying 512 blocks into position 39351...
Copying 512 blocks into position 38839...
Copying 512 blocks into position 38327...
Copying 512 blocks into position 37815...
Copying 512 blocks into position 37303...
Copying 512 blocks into position 36791...
Copying 512 blocks into position 36279...
Copying 512 blocks into position 35767...
Copying 512 blocks into position 35255...
Copying 512 blocks into position 34743...
Copying 512 blocks into position 34231...
Copying 512 blocks into position 33719...
Copying 155 blocks into position 32615...
Copying 1 blocks into position 32849...
Copying 356 blocks into position 33363...
Copying 512 blocks into position 32103...
Copying 512 blocks into position 31591...
Copying 512 blocks into position 31079...
Copying 512 blocks into position 30567...
Copying 303 blocks into position 30052...
Copying 209 blocks into position 30358...
Copying 512 blocks into position 29540...
Copying 512 blocks into position 29028...
Copying 512 blocks into position 28516...
Copying 512 blocks into position 28004...
Copying 512 blocks into position 27492...
Copying 512 blocks into position 26980...
Copying 512 blocks into position 26468...
Copying 512 blocks into position 25956...
Copying 512 blocks into position 25444...
Copying 512 blocks into position 24932...
Copying 512 blocks into position 24420...
Copying 512 blocks into position 23908...
Copying 512 blocks into position 23396...
Copying 512 blocks into position 22884...
Copying 512 blocks into position 22372...
Copying 512 blocks into position 21860...
Copying 512 blocks into position 21348...
Copying 512 blocks into position 20836...
Copying 512 blocks into position 20324...
Copying 512 blocks into position 19812...
Copying 512 blocks into position 19300...
Copying 512 blocks into position 18788...
Copying 512 blocks into position 18276...
Copying 512 blocks into position 17764...
Copying 512 blocks into position 17252...
Copying 1 blocks into position 0...
Copying 512 blocks into position 16740...
Copying 177 blocks into position 322988...
Copying 512 blocks into position 16228...
Copying 512 blocks into position 322476...
Copying 512 blocks into position 15716...
Copying 512 blocks into position 321964...
Copying 512 blocks into position 15204...
Copying 512 blocks into position 321452...
Copying 512 blocks into position 14692...
Copying 512 blocks into position 320940...
Copying 512 blocks into position 14180...
Copying 512 blocks into position 320428...
Copying 512 blocks into position 13668...
Copying 512 blocks into position 319916...
Copying 512 blocks into position 13156...
Copying 512 blocks into position 319404...
Copying 512 blocks into position 12644...
Copying 512 blocks into position 318892...
Copying 512 blocks into position 12132...
Copying 512 blocks into position 318380...
Copying 512 blocks into position 11620...
Copying 512 blocks into position 317868...
Copying 512 blocks into position 11108...
Copying 512 blocks into position 317356...
Copying 512 blocks into position 10596...
Copying 512 blocks into position 316844...
Copying 512 blocks into position 10084...
Copying 512 blocks into position 316332...
Copying 512 blocks into position 9572...
Copying 512 blocks into position 315820...
Copying 512 blocks into position 9060...
Copying 156 blocks into position 315304...
Copying 5 blocks into position 315461...
Copying 351 blocks into position 315469...
Copying 512 blocks into position 8548...
Copying 512 blocks into position 314792...
Copying 512 blocks into position 8036...
Copying 512 blocks into position 314280...
Copying 512 blocks into position 7524...
Copying 512 blocks into position 313768...
Copying 512 blocks into position 7012...
Copying 512 blocks into position 313256...
Copying 512 blocks into position 6500...
Copying 512 blocks into position 312744...
Copying 512 blocks into position 5988...
Copying 512 blocks into position 312232...
Copying 512 blocks into position 5476...
Copying 512 blocks into position 311720...
Copying 512 blocks into position 4452...
Copying 512 blocks into position 311208...
Copying 512 blocks into position 2404...
Copying 512 blocks into position 310696...
Copying 512 blocks into position 4964...
Copying 512 blocks into position 310184...
Copying 512 blocks into position 3940...
Copying 512 blocks into position 309672...
Copying 512 blocks into position 3428...
Copying 512 blocks into position 309160...
Copying 512 blocks into position 2916...
Copying 512 blocks into position 308648...
Copying 512 blocks into position 308136...
Copying 512 blocks into position 307624...
Copying 232 blocks into position 232095...
Copying 280 blocks into position 232332...
Copying 512 blocks into position 231583...
Copying 512 blocks into position 231071...
Copying 512 blocks into position 230559...
Copying 512 blocks into position 230047...
Copying 432 blocks into position 196175...
Copying 1 blocks into position 196608...
Copying 2 blocks into position 229376...
Copying 1 blocks into position 229457...
Copying 76 blocks into position 229971...
Copying 36 blocks into position 195660...
Copying 476 blocks into position 195699...
Copying 512 blocks into position 195148...
Copying 512 blocks into position 194636...
Copying 486 blocks into position 194123...
Copying 26 blocks into position 194610...
Copying 512 blocks into position 193611...
Copying 512 blocks into position 193099...
Copying 512 blocks into position 192587...
Copying 512 blocks into position 192075...
Copying 512 blocks into position 191563...
Copying 512 blocks into position 191051...
Copying 512 blocks into position 190539...
Copying 512 blocks into position 190027...
Copying 512 blocks into position 189515...
Copying 512 blocks into position 189003...
Copying 512 blocks into position 188491...
Copying 512 blocks into position 187979...
Copying 318 blocks into position 187466...
Copying 194 blocks into position 187785...
Copying 512 blocks into position 186954...
Copying 512 blocks into position 186442...
Copying 512 blocks into position 185930...
Copying 512 blocks into position 185418...
Copying 512 blocks into position 184906...
Copying 512 blocks into position 184394...
Copying 512 blocks into position 183882...
Copying 512 blocks into position 183370...
Copying 512 blocks into position 182858...
Copying 512 blocks into position 182346...
Copying 512 blocks into position 181834...
Copying 512 blocks into position 181322...
Copying 512 blocks into position 180810...
Copying 512 blocks into position 180298...
Copying 512 blocks into position 179786...
Copying 512 blocks into position 179274...
Copying 512 blocks into position 178762...
Copying 512 blocks into position 178250...
Copying 512 blocks into position 177738...
Copying 512 blocks into position 177226...
Copying 43 blocks into position 176707...
Copying 135 blocks into position 176751...
Copying 105 blocks into position 176891...
Copying 229 blocks into position 176997...
Copying 512 blocks into position 176195...
Copying 512 blocks into position 175683...
Copying 512 blocks into position 175171...
Copying 512 blocks into position 174659...
Copying 512 blocks into position 174147...
Copying 180 blocks into position 173632...
Copying 332 blocks into position 173815...
Copying 512 blocks into position 173120...
Copying 131 blocks into position 172606...
Copying 381 blocks into position 172739...
Copying 512 blocks into position 172094...
Copying 512 blocks into position 171582...
Copying 512 blocks into position 171070...
Copying 512 blocks into position 170558...
Copying 512 blocks into position 170046...
Copying 256 blocks into position 169525...
Copying 22 blocks into position 169786...
Copying 234 blocks into position 169812...
Copying 512 blocks into position 169013...
Copying 512 blocks into position 168501...
Copying 33 blocks into position 167766...
Copying 126 blocks into position 167974...
Copying 68 blocks into position 168143...
Copying 285 blocks into position 168216...
Copying 87 blocks into position 167028...
Copying 177 blocks into position 167120...
Copying 127 blocks into position 167472...
Copying 121 blocks into position 167645...
Copying 512 blocks into position 166516...
Copying 512 blocks into position 166004...
Copying 512 blocks into position 165492...
Copying 512 blocks into position 164980...
Copying 512 blocks into position 164468...
Copying 475 blocks into position 130596...
Copying 1 blocks into position 131072...
Copying 2 blocks into position 163840...
Copying 1 blocks into position 163921...
Copying 33 blocks into position 164435...
Copying 512 blocks into position 130084...
Copying 512 blocks into position 129572...
Copying 512 blocks into position 129060...
Copying 512 blocks into position 128548...
Copying 512 blocks into position 128036...
Copying 512 blocks into position 127524...
Copying 512 blocks into position 127012...
Copying 512 blocks into position 126500...
Copying 512 blocks into position 125988...
Copying 512 blocks into position 125476...
Copying 512 blocks into position 124964...
Copying 512 blocks into position 124452...
Copying 512 blocks into position 123940...
Copying 512 blocks into position 123428...
Copying 512 blocks into position 122916...
Copying 512 blocks into position 122404...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Skipping command zero...
Done! Output image: F:\AmlogicKitchen-master\tmp\system.img
已复制         1 个文件。
已复制         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
移动了         1 个文件。
已复制         1 个文件。
"DDR.USB is missing, copy DDR.USB to level1 dir"
请按任意键继续. . .
"UBOOT.USB is missing, copy UBOOT.USB to level1 dir"
请按任意键继续. . .
"aml_sdc_burn.UBOOT is missing, copy aml_sdc_burn.UBOOT to level1 dir"
请按任意键继续. . .
"meson1.PARTITION is missing, copy meson1.PARTITION to level1 dir"
请按任意键继续. . .
"platform.conf is missing, copy platform.conf to level1 dir"
请按任意键继续. . .
[Msg]Pack Item[PARTITION   ,         _aml_dtb] from (level1\_aml_dtb.PARTITION),sz[0xfbae]B,
[Msg]Pack Item[ini         ,     aml_sdc_burn] from (level1\aml_sdc_burn.ini),sz[0x18a]B,
[Msg]Pack Item[PARTITION   ,             boot] from (level1\boot.PARTITION),sz[0xd10800]B,ft[normal]
[Msg]Pack Item[PARTITION   ,       bootloader] from (level1\bootloader.PARTITION),sz[0x14e970]B,ft[normal]
[Msg]Pack Item[PARTITION   ,             dtbo] from (level1\dtbo.PARTITION),sz[0x1b6]B,
[Msg]Pack Item[PARTITION   ,             logo] from (level1\logo.PARTITION),sz[0xfe080]B,ft[normal]
[Msg]Pack Item[PARTITION   ,              odm] from (level1\odm.PARTITION),sz[0x75070]B,ft[sparse]
[Msg]Pack Item[PARTITION   ,          product] from (level1\product.PARTITION),sz[0x3b6e0e0]B,ft[sparse]
[Msg]Pack Item[PARTITION   ,         recovery] from (level1\recovery.PARTITION),sz[0x1415800]B,ft[normal]
[Msg]Pack Item[PARTITION   ,           system] from (level1\system.PARTITION),sz[0x2db02bec]B,ft[sparse]
[Msg]Pack Item[PARTITION   ,           vbmeta] from (level1\vbmeta.PARTITION),sz[0x40]B,
[Msg]Pack Item[PARTITION   ,           vendor] from (level1\vendor.PARTITION),sz[0xf3db880]B,ft[sparse]
[Msg]version:0x2 crc:0x10e31abe size:1122261536 bytes[1070MB]
Pack image[out\B863AV3.2M-220821_fota.img] OK
Done.
Done.
请按任意键继续. . .
![image](https://user-images.githubusercontent.com/9524903/194578438-d1814918-0992-44b7-9753-64d553d5af93.png)

**Comment by althafvly** [comment]
Did you copy the missing files?. You can't use that image without those files.

**Comment by zengfr** [comment]
> Did you copy the missing files?. You can't use that image without those files.

1  origina img file is ok .
2  unpack origina file and  edit  
3  pack_level1_fota
4  pack_zip_to_aml  
5  out  img  is not ok .

**Comment by althafvly** [comment]
```
"DDR.USB is missing, copy DDR.USB to level1 dir"
"UBOOT.USB is missing, copy UBOOT.USB to level1 dir"
"aml_sdc_burn.UBOOT is missing, copy aml_sdc_burn.UBOOT to level1 dir"
"meson1.PARTITION is missing, copy meson1.PARTITION to level1 dir"
"platform.conf is missing, copy platform.conf to level1 dir"
```

You didn't copy the missing files

```
[Msg]Pack Item[PARTITION , _aml_dtb] from (level1_aml_dtb.PARTITION),sz[0xfbae]B,
[Msg]Pack Item[ini , aml_sdc_burn] from (level1\aml_sdc_burn.ini),sz[0x18a]B,
[Msg]Pack Item[PARTITION , boot] from (level1\boot.PARTITION),sz[0xd10800]B,ft[normal]
[Msg]Pack Item[PARTITION , bootloader] from (level1\bootloader.PARTITION),sz[0x14e970]B,ft[normal]
[Msg]Pack Item[PARTITION , dtbo] from (level1\dtbo.PARTITION),sz[0x1b6]B,
[Msg]Pack Item[PARTITION , logo] from (level1\logo.PARTITION),sz[0xfe080]B,ft[normal]
[Msg]Pack Item[PARTITION , odm] from (level1\odm.PARTITION),sz[0x75070]B,ft[sparse]
[Msg]Pack Item[PARTITION , product] from (level1\product.PARTITION),sz[0x3b6e0e0]B,ft[sparse]
[Msg]Pack Item[PARTITION , recovery] from (level1\recovery.PARTITION),sz[0x1415800]B,ft[normal]
[Msg]Pack Item[PARTITION , system] from (level1\system.PARTITION),sz[0x2db02bec]B,ft[sparse]
[Msg]Pack Item[PARTITION , vbmeta] from (level1\vbmeta.PARTITION),sz[0x40]B,
[Msg]Pack Item[PARTITION , vendor] from (level1\vendor.PARTITION),sz[0xf3db880]B,ft[sparse]
[Msg]version:0x2 crc:0x10e31abe size:1122261536 bytes[1070MB]
Pack image[out\B863AV3.2M-220821_fota.img] OK
```
