### ISSUE TITLE
Unpacking level 1 error

### ISSUE THREAD

**Issue by jayavanth** [althafvly/AmlogicKitchen#13]
Hi I'm trying to unpack Level 1 for a S905W2 ROM which has Android 11 and I'm getting this error

```
./unpack.sh 
.....................
Amlogic Kitchen
.....................
.....................
Select level 1,2,3 or q/Q to exit: 
1
Deleting existing level1
.....................
Amlogic Kitchen
.....................
No files found in /in
```

How can I fix it? Thanks!

**Comment by althafvly** [comment]
`No files found in /in`

**Comment by jayavanth** [comment]
> `No files found in /in`

Oh I see. So should I put the firmware in `/in`?

**Comment by jayavanth** [comment]
Thanks! I'll try it out. I need to compile the binary for ARM or switch to my x86 computer

**Comment by althafvly** [comment]
There won't support for arm. Some of the binaries used here are not opensource.
