### ISSUE TITLE
Level2 Packing Unable To Create Super Image 

### ISSUE THREAD

**Issue by Adam1986** [althafvly/AmlogicKitchen#17]
Good evening, 

Sorry I'm quite new to this tool.  Successfully unpacked an image up to level2 for my S905X4 Transpeed box.  Removed a bit of junk from the file system and added a small file.  

Every time i try to pack this back I simply get the following error:

```
Resizing the filesystem on level2\odm_a.img to 599 (4k) blocks.

The filesystem on level2\odm_a.img is now 599 (0k) blocks long.

Invalid number.  Numbers are limited to 32-bits of precision.
Unable to create super image, recreated images are too big.
Cleanup some files before retrying
Needed space: 2230022144
Available maximum space: 2415919104

Press any key to continue . . .
```
This is happening on Windows 11, hoping you can assist?

Thanks

**Comment by althafvly** [comment]
Windows scripts are no longer support. Please reopen if you face this issue in WSL or Linux.
