### ISSUE TITLE
Does not handle super_all_empty.img

### ISSUE THREAD

**Issue by keshto** [althafvly/AmlogicKitchen#2]
https://github.com/xKern/AmlogicKitchen/blob/398a30da773b92aedee963c3f8b0024499a35347/pack_zip_to_aml.sh#L131

With OTAs that are upgrading android 9 to 10 there is a `super_all_empty.img` file which is used when creating first dynamic partitions. Once that is setup the old idea of a system partition is not used. USB burn tool will throw a "diskInit" error.

**Comment by althafvly** [comment]
That's an empty partition, there's nothing inside it. Also this tool doesn't support super partition for creating aml from zip or zip from aml. You can use this tool to repack working aml images with super partition.

If you want to create an aml package from dump then, you need to edit the config files manually to make it work.
