### ISSUE TITLE
SyntaxWarning: invalid escape sequence

### ISSUE THREAD

**Issue by bbdoc** [althafvly/AmlogicKitchen#21]
Hi,

When unpacking (level 2) using python under windows 11, I'm getting a bunch of those errors :

```
C:\AMLOGI~1\bin\common\imgextractor.py:622: SyntaxWarning: invalid escape sequence '\+'
  3, '/' + dirr + '/lost\+found' + ' ' + c.split(" ")[1])
C:\AMLOGI~1\bin\common\imgextractor.py:628: SyntaxWarning: invalid escape sequence '\+'
  3, '/lost\+found' + ' u:object_r:rootfs:s0')
```

I'm using Python 3.12.1

As far as as I can see, everything was still unpacked successfully but I thought it was worth reporting it.

Thanks

**Comment by althafvly** [comment]
It's warnings. Also windows scripts are no longer maintained.
