### ISSUE TITLE
Using of password.bin for dumping device

### ISSUE THREAD

**Issue by catmengi** [althafvly/AmlogicKitchen#23]
I have xiaomi mi box s device(MDZ-22-AB), i find out that i can modify 8.1 android image but my mi box have broken MAC addr on versions below ATV 9, so i interested in dumping android 9 / 12 firmware straight from mi box but device have locked emmc and need password.bin but i didnt figure out how to make dump.sh use it

**Comment by althafvly** [comment]
At the moment, there's no option for this.
