### ISSUE TITLE
Error "lpmake"

### ISSUE THREAD

**Issue by duymanhtc09** [althafvly/AmlogicKitchen#24]
I got an error when I repack level2 for amlogic, ATV10 rom "lpmake E 09-10 09:13:32 1345 5008 builder.cpp:540] [liblp]Could not find partition group: amlogic_dynamic_partitions_a
Could not add partition: system"
Previously when I unpack level2 I got the result files 'odm.img' product.img' 'system.img' 'vendor.img' and 1 folder "config"

`Amlogic Kitchen
.....................
Select level 1,2,3 or q/Q to exit: 2
lpmake E 09-10 09:13:32  1345  5008 builder.cpp:540] [liblp]Could not find partition group: amlogic_dynamic_partitions_a
Could not add partition: system
Done.

![error-edit](https://github.com/user-attachments/assets/caba1587-afaf-47f3-943d-16133af560eb)

**Comment by althafvly** [comment]
Windows is no longer supported.
