### ISSUE TITLE
Windows repack makes read only partition.

### ISSUE THREAD

**Issue by dister520** [althafvly/AmlogicKitchen#3]
1. take an image and unpack level 1.

Level1 repack shows no issues

 2. going into adb shell user is allowed to su and get # 
 3. Unpack 2 and repack both 2 and 1
 4. Try step 2 and user receives su not permitted. Image is read only.
 
 much thanks

**Comment by althafvly** [comment]
Are you trying to get root access?. If so, this tool does not add super user access into a rom. You need manually add it.

**Comment by dister520** [comment]
Attached is the screenshot of the rom from vendor which allows su from shell. It appears that after I pack with 2 the item is changed. Wanting shell to have access to su like the vendor rom.
![16F89799-40CD-4CDC-B452-11B5C08CDC4B](https://user-images.githubusercontent.com/25096819/169910522-9634d38a-0af8-4858-820b-701fe6c04499.jpeg)

**Comment by dister520** [comment]
I believe this is an issue related to unpack and not sure if fs_context and or permissions are changed by the imgextractor?

**Comment by althafvly** [comment]
Just unpacking and packing won't remove su, if you already have. Link me your firmware, i can check

**Comment by dister520** [comment]
thanks emailed link to the gmail account in profile.

**Comment by althafvly** [comment]
I just repacked your firmware. it seems su is present here. hasnt removed and which linux distro are you running?.

**Comment by dister520** [comment]
Great please see the permission of su in system/xbin/su. 
The permissions will have changed and be different than the above screenshot.

**Comment by dister520** [comment]
Before packing the system would allow su without root. After repacking su would require adb-root.

**Comment by althafvly** [comment]
- You can add/change permission in level2/config/*_fs_config for each files and folder manually.

- adb root is only for development builds, which means your build is userdebug/eng.

**Keep in mind that this is dev tool, try everything at your own risk.**

**Comment by dister520** [comment]
Correct it’s a debug build. And not sure why when I repack fs file it does not function as a debug build.


Sent from Yahoo Mail for iPhone


On Thursday, May 26, 2022, 11:41 AM, Mohammed Althaf ***@***.***> wrote:



   
   -    
You can add/change permission in level2/config/*_fs_config for each files and folder manually.

   -    
adb root is only for development builds, which means your build is userdebug/eng.


Keep in mind that this is dev tool, try everything at your own risk.
