### ISSUE TITLE
amlogic android 9.0 image can not pack

### ISSUE THREAD

**Issue by hutuxiansheng** [althafvly/AmlogicKitchen#7]
The amlogic android 9.0 image is unpacked and repackaged. After burning to the device, it starts abnormally, and the device reports an abnormal partition.

**Comment by althafvly** [comment]
I can't help without proper explanation, even the modification you done to image will cause issues.

**Comment by hutuxiansheng** [comment]
The firmware has not been modified, just unpack the system partition, and then repackage it to the firmware. Burn the new firmware to the device and it will not start.

I will provide more details later，Thank you for your answer！

**Comment by althafvly** [comment]
Re-open once you have more details on this issue.
