### ISSUE TITLE
repack super.img bug

### ISSUE THREAD

**Issue by LeChenOS** [althafvly/AmlogicKitchen#9]
Unable to create super image, recreated images are too big.
Cleanup some files before retrying
Needed space: 2453938176
Available maximum space: 5368709120

I've deleted a lot of files to make room

**Comment by althafvly** [comment]
link firmware

**Comment by LeChenOS** [comment]
https://drive.google.com/file/d/1W58_j-rUxNVexTW_HHm7-ub7m11MGo-s/view?usp=sharing

**Comment by althafvly** [comment]
No issues found, i was able to unpack/repack image with ease.
